import { useState } from "react";
import { WalletInput } from "@/components/WalletInput";
import { AnalysisView } from "@/components/AnalysisView";
import { Shield, Eye, Lock, Zap } from "lucide-react";
import { analyzeWallet, type AnalysisResult } from "@/lib/api";
import { toast } from "sonner";
const Index = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [analysisData, setAnalysisData] = useState<AnalysisResult | null>(null);
  const handleAnalyze = async (wallet: string) => {
    setIsLoading(true);
    try {
      const data = await analyzeWallet(wallet);
      setAnalysisData(data);
      toast.success("Analysis complete");
    } catch (error) {
      console.error("Analysis failed:", error);
      toast.error(error instanceof Error ? error.message : "Analysis failed");
    } finally {
      setIsLoading(false);
    }
  };
  if (analysisData) {
    return <AnalysisView data={analysisData} onBack={() => setAnalysisData(null)} />;
  }
  return <div className="min-h-screen bg-background relative overflow-hidden">
      {/* Background grid pattern */}
      <div className="absolute inset-0 bg-grid-pattern opacity-30" />
      
      {/* Gradient orbs */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-primary/5 rounded-full blur-3xl" />

      <div className="relative z-10">
        {/* Header */}
        <header className="container mx-auto px-4 py-6">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10 glow-primary">
              <Shield className="w-6 h-6 text-primary" />
            </div>
            <span className="font-semibold text-lg text-foreground">Solana Privacy Copilot</span>
          </div>
        </header>

        {/* Hero */}
        <main className="container mx-auto px-4 pt-16 pb-24">
          <div className="max-w-4xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium mb-8 animate-fade-in-up">
              <Eye className="w-4 h-4" />
              AI-Powered Privacy Analysis
            </div>
            
            <h1 className="text-4xl md:text-6xl font-bold text-foreground mb-6 animate-fade-in-up" style={{
            animationDelay: "0.1s"
          }}>
              Understand Your Wallet's{" "}
              <span className="text-gradient-primary">Privacy Risk</span>
            </h1>
            
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-12 animate-fade-in-up" style={{
            animationDelay: "0.2s"
          }}>Quantify linkability, detect metadata leakage, and get mitigation strategies for your Solana wallet.</p>

            <div className="animate-fade-in-up" style={{
            animationDelay: "0.3s"
          }}>
              <WalletInput onSubmit={handleAnalyze} isLoading={isLoading} />
            </div>

            {/* Feature highlights */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-24 animate-fade-in-up" style={{
            animationDelay: "0.4s"
          }}>
              <div className="card-cyber rounded-xl p-6 text-left">
                <div className="p-2.5 rounded-lg bg-primary/10 w-fit mb-4">
                  <Eye className="w-5 h-5 text-primary" />
                </div>
                <h3 className="font-semibold text-foreground mb-2">Privacy Score</h3>
                <p className="text-sm text-muted-foreground">
                  Composite heuristic scoring across 6 privacy dimensions with clear risk bands.
                </p>
              </div>
              
              <div className="card-cyber rounded-xl p-6 text-left">
                <div className="p-2.5 rounded-lg bg-primary/10 w-fit mb-4">
                  <Zap className="w-5 h-5 text-primary" />
                </div>
                <h3 className="font-semibold text-foreground mb-2">Solana Native</h3>
                <p className="text-sm text-muted-foreground">
                  Deep analysis of fee payers, signers, program interactions, and memo fields via Helius.
                </p>
              </div>
              
              <div className="card-cyber rounded-xl p-6 text-left">
                <div className="p-2.5 rounded-lg bg-primary/10 w-fit mb-4">
                  <Lock className="w-5 h-5 text-primary" />
                </div>
                <h3 className="font-semibold text-foreground mb-2">AI Guidance</h3>
                <p className="text-sm text-muted-foreground">
                  Actionable remediation strategies generated by AI based on your specific risks.
                </p>
              </div>
            </div>
          </div>
        </main>

        {/* Footer */}
        <footer className="container mx-auto px-4 py-8 border-t border-border">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-muted-foreground text-sm">
              Solana Privacy Copilot v1.0 • Built for Solana Privacy Hackathon 2026
            </p>
            <p className="text-muted-foreground text-sm">
              Powered by Helius RPC • Devnet anchoring available
            </p>
          </div>
        </footer>
      </div>
    </div>;
};
export default Index;